### ISSUE TITLE
License is non-free

### ISSUE THREAD

**Issue by ghost** [open-power/docs#12]
License prevents modification, which is probably not what we want when documenting free software.

**Comment by williamspatrick** [comment]
I agree.  We had this discussion before and I don't know what came of it.

**Comment by macpijan** [comment]
Hello.

We are going through the coreboot port for POWER9 and need to understand the details on the low level. We often need to understand the flow from the code or debug Hostboot logs, rather from documentation, as there is usually not enough information   out there.

We are producing a lot of documentation and I believe many of it could be a good fit in this repository (after some adjustments). Some examples are:
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/porting.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/mss_vpd.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/pnor_layout.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/_fetch_and_insert_vpd_rings/devnotes/mvpd_partition_structure.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/initial_cpu_state.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/ppc.md
- https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/sbe.md

The README says:

```
As always is the case with documentation, it usually needs some updates. So feel free to do it yourself :) or touch base with us on the mailing lists.
```

while the license says (https://github.com/open-power/docs/blob/master/LICENSE#L37): 

```
You may not modify this documentation.
```

Doesn't it basically **prevent** people from contributing here?

Another issue on that matter: https://github.com/open-power/docs/issues/3
