### ISSUE TITLE
About petitboot-plugins.txt

### ISSUE THREAD

**Issue by sword-huang** [open-power/docs#14]
I install my test plugin as below:

/ # pb-plugin install /hehlloorld-1.0.pb-plugin 

File 'hehlloorld-1.0.pb-plugin' has the following sha256 checksum:

de9d08116cda0163166c55a0cf6a5ba01c7128546df4c7c73967e43547e80596

Do you want to install this plugin? (y/N)
y
3 blocks
Plugin installed
OpenPower Foundation: Hello World Petitboot Plugin Example 1
  (version 1.0)

Where can I launch it?

**Comment by williamspatrick** [comment]
@stewart-ibm - I'm guessing nobody from your team saw this.

**Comment by jk-ozlabs** [comment]
@sword-huang : the binaries that your plugin has installed (ie., those listed in `PLUGIN_EXECUTABLES`) are now available as standard command-line commands at the shell.

**Comment by sword-huang** [comment]
Get it! Thanks!
